# Generated by Django 3.2.15 on 2022-12-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_alter_items_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footballers',
            fields=[
                ('id_footballer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('id_team', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'footballers',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.footballers'),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
